### ISSUE TITLE
Exclude auto migration and auto seed

### ISSUE THREAD

**Issue by bashet** [mnabialek/laravel-modular#9]
Hi,

Sorry to bother you. Just wandering if there is a way to exclude module specific migration and seed from migrate command and seed command!.

My intention is: as this is module based concept! So I would like to migrate module specific migtation separately for each module with an installation procedure. Same thing for seed too.

**Comment by mnabialek** [comment]
In general there is no option to do that. In real application in fact you will be using all modules so you don't want to migrate or seed individual ones because they might rely also on other modules. If you want to turn off individual packages from migrating/seeding, you can deactivate options (add `active` option with `false` value). And about seeding you have `module:seed` option where you can run seeds from selected modules.

**Comment by bashet** [comment]
Hi,

Is there any possibility we can do those below activities for each modules without distrubing the whole system considering we may have some migration and seeding activity?
- Install 
- Un-install 
- Re-install
- Upgrade
- downgrade

**Comment by mnabialek** [comment]
No, this package doesn't need to install/uninstall modules and so on. You can just copy module directory, add entry to config where modules are listed (make sure it's active) and you are done. If you want to downgrade, you need to create custom logic to do that, you cannot use this package to upgrade/downgrade your modules
